export default {
  printWidth: 160,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  vueIndentScriptAndStyle: true,
  singleQuote: true,
  quoteProps: 'as-needed',
  bracketSpacing: true,
  trailingComma: 'es5',
  bracketSameLine: true,
  jsxSingleQuote: false,
  arrowParens: 'always',
  insertPragma: false,
  requirePragma: false,
  proseWrap: 'always',
  htmlWhitespaceSensitivity: 'ignore',
  endOfLine: 'crlf',
  rangeStart: 0,
};
