export const PAGE_ENUM = {
  LOGIN_PATH: '/login',
  LOGIN_NAME: 'Login',
  LOGIN_TITLE: '登录',
  HOME_PATH: '/home',
  HOME_NAME: 'Home',
  HOME_TITLE: '首页',
  HOME_ICON: 'HomeOutlined',
  PAGE_PATH: '/page',
  PAGE_NAME: 'Page',
  ERROR_PAGE_NAME: 'ErrorPage',
  ERROR_PAGE_TITLE: '错误404',
  ERROR_CHILD_PAGE_NAME: 'ErrorPageSon',
  REDIRECT_PATH: '/redirect',
  REDIRECT_NAME: 'Redirect',
  REDIRECT_PAGE_NAME: 'RedirectPage',
  REDIRECT_PAGE_TITLE: '重定向页面',
  REDIRECT_CHILD_PAGE_NAME: 'RedirectPageSon',
  SETTING_PATH: '/setting',
  SETTING_NAME: 'Setting',
  SETTING_TITLE: '设置',
  SETTING_ACCOUNT_PATH: '/setting/account',
  SETTING_ACCOUNT_NAME: 'SettingAccount',
  SETTING_ACCOUNT_TITLE: '个人设置',
  SETTING_PASSWORD_PATH: '/setting/password',
  SETTING_PASSWORD_NAME: 'SettingPassword',
  SETTING_PASSWORD_TITLE: '密码设置',
};
