import {
  SettingOutlined,
  SearchOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  FullscreenOutlined,
  FullscreenExitOutlined,
  PoweroffOutlined,
  GithubOutlined,
  LockOutlined,
  ReloadOutlined,
  LogoutOutlined,
  UserOutlined,
  CheckOutlined,
} from '@/utils/icons';

export default {
  SettingOutlined,
  LockOutlined,
  GithubOutlined,
  SearchOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  FullscreenOutlined,
  FullscreenExitOutlined,
  PoweroffOutlined,
  ReloadOutlined,
  LogoutOutlined,
  UserOutlined,
  CheckOutlined,
};
