# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
    # tags:
    # - 'bmw-*'

jobs:
  build:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # 获取源码，使用actions/checkout@v2
        uses: actions/checkout@v2

      # - name: Install & Build # 安装依赖打包静态资源
      #   run: |
      #     yarn
      #     yarn build

      - name: Deploy to Server # 部署到云服务器，使用easingthemes/ssh-deploy@v2.1.1，通过ssh的方式连接
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          # SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # 私钥，公钥拷贝到服务器在/root/.ssh/authorized_keys中
          # ARGS: ${{ secrets.ARGS }} # 对于任何初始/必需的rsync标志，默认-avzr --delete，如果目录下有其他不可删除文件或文件夹可以用--exclude忽略，如--exclude /uploads/
          # SOURCE: "public/" # 源目录
          # REMOTE_HOST: ${{ secrets.REMOTE_HOST }} # 服务器地址
          # REMOTE_PORT: ${{ secrets.REMOTE_PORT }} # ssh连接端口号
          # REMOTE_USER: root # 连接用户名
          # TARGET: ${{ secrets.REMOTE_TARGET }} # 目标部署目录
          SSH_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----
MIIJKgIBAAKCAgEAy0MFeL5N+toXWBntITSTADOHtJ/2cu8JBwnF+AfJIpNOxkyM
A5mwMV3zn294huqP+9Sg0isn247Erwf3xhBHRNkVEvYUAmRQRClE6P1tfMQExDWo
AvBoTNSuF9cBAFomN918ZakoyzP339nPR/MMqL8pZ3gKcIInylTVb45XK4xl7IxY
oldFYyC4odJ7mebYUvWUuPzwTePg48UQ5riip03J3qlJ+fMePBM/phlRggmwisaR
B7HjemsEFnMbQCveSwxhqoeQKlkWV73dIH8UnZM33j0KRb9ktCPHzZ6Nc1nMXl8P
WY2WMr0zq8f3mo2xgIuR8IGfj0jD7L+hSIfS3sJT8fZ1lb5BshbMWP1PQwpxeQm0
5TohZgTFw2LQ3i90lZ5ClOLvW9bbhfoKmLBJUzWFf9466Ysig6mEmEEnT3+iVhhU
Pjz6ZqtE9psFNQVnW+yCVsoglDj7MqAzeLFMwJqN/laqRvL/0XJqwPoFJQPE9ZQ2
aIruCFuz+sm4sSCeTXFU4KvbjdOdhJ102FRvzKzYA2vZYnxqeBguTu1WnmaHDixv
mwUnxAzs38VwEpaypESotPqLrToRTWdmI4nAaIbKarfyrn3hDmDfqbfSFmaTh5AF
abo3rPQ04m0lFxx0EMoP0xopVRfeThHMfk5xYMCtgAACSLZ7j+JkqcSO5f8CAwEA
AQKCAgEAq7ap97AlZoc582arqkKk8SWXPmNoqv3/DWAXS4sgQ0JY6TMfkacTbxEk
0As2shuUmbWuSv7ERDpfNFKx4jQ8URBnOkaC7uZZ3MtUeNQn26ApOqzti9YW9tkx
Xdh38xk1cjp9bdCzMr9rZ0O1Vd4hUqlzzAJgJ139SXPTf9OrFpIcRPLnqfW6G503
/RU47/JRy/vFsWWViOe7RBBmT9OpLVeM87rmUO8vGqdUPPjkn8uZxhMr0GlaeD/S
Czkgy1yEBbinBY5Sn0P1mRg/p8VT4C7PosLEW9nttDUKBU4tx0YUXaFG8WuoeKLX
9QYQyhNr4eGG37xR1JUvV2EoWoLMA3xGWoLD11S5G2nOgSVHJsXS23VdfYn05k4h
NCJ0WUFfB9iBCxQ6KZ0UP6U1lSBu1QUqX2fbPc9qf0p1leYw/vdGiEaCef9ie7MN
GLZF+rNEDWdu5U1zecJR3G3dunutN+h5raH9Z0gtZAqxCwd3PjE+j/is0gLOWfqX
7G2gSgDPqYkoiWYkc6oGAb9OT8VynS4OTWMnp0xZGOlHj31TAdgbt1Bs+DtV4vYP
HLTGqKyFOeIQwqKWyMHQLkn2sKIr+Iw+oRsEpFCzIBsf+KKCNKISFBUpvj1RText
tS+wyiJds00s15XbaMl2tuZObyYMlJv7mLtFQD22ZOHRP6ZrKfkCggEBAO0/TSue
96qLaZIgi3qsTt7qc98TbIR85QdA2KHDKIy8CkVkuB0itwBieBW7N1Kfe2LJ8TNO
95LTvMvKWBCLcxqEf2vImRskJS2xGnEds+uVzZRpjAu8oVekIifxnqcKlQ3Dq5+q
LIzqkgXAOIfNPCzWq/rZpJrWPoZE5bZdU2/t6RdPpgkgdZ85u9spvQ6ru0bN4yfY
b39+0Ll2Q6s8/DDROXGn/fnTCpDAG2L8uzONHz+zPAHpJYQDcSN7zuuLpE3S5YVT
kk9EbfDgT6i5AGd2eXcNENJFWvwTUx/VgOY2TMWsXNtUIQcAWjnmRS8uyBDpKD44
zti/a5KyFkPfM10CggEBANtUBiIfDx5XHBe0onMFOEZkzWR654N+q5SetllPdk78
b3oGXV2V8cJa50Hi/tmPWdKwcFtxmqGmif5C96WtG3CnyMUV4KttSghwCkHaS0cq
eXEpUaEc+LY8/Kc1CZJMZmdjzDoPFUqU8HLVf8rl7OpicBdzjHB8kQG58BnGr/6T
KufX1rJxgucTY+WysJxFm2weIaVkKUbV8Y2vl7aN6xX/TCr59Hrj6QXxQ4XSRr/z
1/cnV54if5t9h+ESOiDn7bFjzgstMfRJ/p6m4BatX1kh04C8JbvG5Xsah1Z+dase
jTJ+C6q3fMuP8RLVXyav88mzhJTPkWNNKpzXaF5EZQsCggEAGWqXrN2p8MZgt/vu
lWTSSkVZxoNBM+xhaOaEjsfmlzUp8Ic6xjxK2Kqz7LgS1DIruMijo3iJQ1yVtEto
JdWarjOVpwllhafYp816ZLXm6Y0x6f1ouHUr38TAuADFm2Wh1EirIT7M6QfUPvN5
2uqc0LzqzcP1Q3VCW4YUCfZzkuEtAIdS5VVp5HX97xvImkLBnHNAK6ufPkxqtgO6
eiTda6luewOhTNtUHW/HP1KOB5bNyzg7bIT6tOrdewyvfUKHhqLaXe83FHDjSlPt
lMjFB1CE8MEglTZC6hBz7kwkNAWLMf4mMIURyLs770oBDW34lv8zhX72gff34U5c
3kaSLQKCAQEAzn5vP9TKISCWXGM+xtfVQcFJ9x4Xth+eX1CGEdPUaU0Vj2dKo/+2
G+wF6mxS0HY8dTaUsiNlGGh5Zx+ZlSxDt27ggV21pvBAUW1a2uExGpGMwNPL/MoQ
B1On86zllA3GI/U7pDXrL8rGDvefV2HeClYffpTVVlqRE3UB7uK3dBEOxjTZ+CsS
uYfx96Ki0J5gVAySVOrWSdDHmUQGrGM1QAKaraOjX8gP7f5WOjndTn+/hvxNa57D
UZuAQJEulSiHCwoSRUeJzpuT0779H5yfNoW4YW3CgOYjzCEP5oktM6yR90XgqhwS
rHya1cZ5zSy/c9lGK+y4zyspwXy00HvIPQKCAQEAzf/IpcBKwt8qNt57lqioKsmI
hpopMbzfzhLu/OeOUyVc0xhUGp5Zzod9RUYQisf9fWZ9VdGzHguqhwZ9bWPT+J3F
6xkUGXfQzk+G30qXgwXzw5S/JKtsxwnLOGZAUX1LWcWivrv30fFOCdPN2WhtYG4d
KrWW6dv+V383t9uJtRjuZs4+riDfc1KiKJKf/Jl/UctxKq6lM5vuOVeQPPqeSg1C
7KSd8+ptxIzOlBQpG8AGuVoy5412lqtSD2rYkX7yrJh9SptP9fs8G1FR3sCysi58
pflFH1DXgi6hLSE0tFDwF1g8rPKEeNwPLp0ASQLaDUoMAlhArkOiduL5meh1Qw==
-----END RSA PRIVATE KEY-----" # 私钥全选复制至SSH_PRIVATE_KEY配置，公钥拷贝到服务器在/root/.ssh/authorized_keys中
          ARGS: "-avzr --delete"
          SOURCE: "public/" # 源目录
          REMOTE_HOST: "120.79.162.189"
          REMOTE_PORT: "38"
          REMOTE_USER: "root" # 连接用户名
          TARGET: "/www/wwwroot/text/"
