# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    tags:
      - 'aba-*'
    branches:
      - dev

jobs:
  buildNestDev:
    if: github.ref_name === 'dev'
    name: build-nest
    runs-on: ubuntu-latest
    steps:
      # 连接到服务器并使用SSH进行部署
      - name: Connect to the server and deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          # 服务器地址
          host: ${{ secrets.SERVER_HOST }}
          # ssh连接端口号
          port: ${{ secrets.SERVER_PORT }}
          # 连接用户名
          username: ${{ secrets.SERVER_USERNAME }}
          # 私钥，到服务器的/root/.ssh/authorized_keys中拷贝
          key: ${{ secrets.SERVER_KEY }}
          # 当出现第一个错误时停止执行命令
          script_stop: true
          # github.ref_name 分支或标记的短参考名称
          script: |
            cd /www/wwwroot/nestApi/
            git reset --hard HEAD
            git fetch origin
            git tag -l -n
            git checkout ${{ github.ref_name }}
            yarn update_dev_pm2
            ls -al

  buildNest:
    if: github.ref_name === 'aba-'
    name: build-nest
    runs-on: ubuntu-latest
    steps:
      # 连接到服务器并使用SSH进行部署
      - name: Connect to the server and deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          # 服务器地址
          host: ${{ secrets.SERVER_HOST }}
          # ssh连接端口号
          port: ${{ secrets.SERVER_PORT }}
          # 连接用户名
          username: ${{ secrets.SERVER_USERNAME }}
          # 私钥，到服务器的/root/.ssh/authorized_keys中拷贝
          key: ${{ secrets.SERVER_KEY }}
          # 当出现第一个错误时停止执行命令
          script_stop: true
          # github.ref_name 分支或标记的短参考名称
          script: |
            cd /www/wwwroot/nestApi/
            git reset --hard HEAD
            git fetch origin
            git tag -l -n
            git checkout ${{ github.ref_name }}
            yarn update_prod_pm2
            ls -al
